### ISSUE TITLE
No active contexts for scope type javax.enterprise.context.RequestScoped

### ISSUE THREAD

**Issue by JavesonYehudi** [wpivotto/vraptor-tasks#21]
Estou tentando criar uma task, mas recebo sempre essa exception ao iniciar a aplicação.

Usando o Vraptor 4.1.0-RC2 e o task 4.2;
Já tentei de tudo, mas não faço ideia do que esteja acontecendo.

FullStack:

`org.jboss.weld.context.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.RequestScoped
	at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:680)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:79)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:78)
	at br.com.caelum.vraptor.tasks.helpers.TriggerBuilder$Proxy$_$$_WeldClientProxy.triggerFor(Unknown Source)
	at br.com.caelum.vraptor.tasks.TaskHandler.whenApplicationStarts(TaskHandler.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:93)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:266)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:253)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:232)
	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:169)
	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:165)
	at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:119)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:112)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:83)
	at br.com.caelum.vraptor.VRaptor.init(VRaptor.java:94)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:262)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:107)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4775)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5452)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by victorguimaraessilva** [comment]
Tambem estou com mesmo erro

**Comment by lucianohdr** [comment]
Se isso for útil para alguém. Esse erro começou a acontecer no nosso projeto quando foi habilitada a propriedade "Eager filter initialization: true" no WildFly 11. O que faz com que a aplicação seja inicializada junto com o WildFly sem precisar que o usuário faça um request no browser. 
Eu fiz um clone do projeto e tentei anotar as classes TaskLinker e TriggerBuilder com @Dependent em vez de @RequestScoped

Eu fiz teste tanto com a propriedade habilitada quando desabilitada e os jobs executaram normalmente. Porém, eu não sei se essa alteração terá algum outro impacto.
